# Generated by Django 5.2.8 on 2025-12-14 09:16
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='last_date',
            field=models.DateTimeField(default=django.utils.timezone.now,help_text='Last date to submit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='topic',
            field=models.CharField(default='Uncategorized', max_length=100),
            preserve_default=False,
        ),
    ]
