# Generated by Django 5.2.8 on 2025-12-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_quiz_last_date_quiz_quiz_time_quiz_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='last_date',
            field=models.DateField(help_text='Last date to submit'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_time',
            field=models.IntegerField(help_text='Duration in minutes'),
        ),
    ]
